### PR TITLE
Migrate CI/CD to GitHub Actions (includes builds for Apple Silicon)

### PR DESCRIPTION
**Pull request by richiksc**
GitHub Actions have nicer integration with the GitHub UI, and it seems to run faster and it is much easier to publish to GitHub Releases, since you don't have to maintain a token. It also has native support for macOS 11.0 runners, which make it easier to cross-compile for ARM Macs.

Succesful build output for the latest commit: https://github.com/richiksc/badlogvis/actions/runs/404341864

Sample release for latest commit: https://github.com/richiksc/badlogvis/releases

Again, feel free to squash the merge if you do choose to merge this.

Closes #9

### CODE REVIEW

**Comment by richiksc** [comment]
This is even more relevant now, as Travis CI have just announced that they are no longer providing free CI minutes to open-source projects. Source: https://news.ycombinator.com/item?id=25338983

**Comment by dominikWin** [comment]
Thanks! I'll take a look at this today.

**Review by dominikWin — APPROVED** [review]
Nice, love the multi architecture builds.

**Comment by richiksc** [comment]
@dominikWin When will we see an official `0.3.4` release?

In addition, I was considering uploading the binaries (at least the Linux/macOS ones) as `.tar.gz` instead, that way we could keep the binaries inside `badlogvis` without having to have the user rename them and they could keep their executable permissions so they wouldn't have to do `chmod +x` either. Perhaps biggest of all, we could potentially bundle an install script so they can just run that and it will install it to their `/usr/local/bin`. I don't know if it would even be necessary, but just a consideration.

**Comment by dominikWin** [comment]
`0.3.4` is just to trigger a new build with these, right?

**Comment by richiksc** [comment]
@dominikWin Yep, just what you usually do - bump the versions in Cargo.toml and the README and tag a release. ~Although, the actual code hasn't really changed, so would it even be a new version?~ You would need to tag a new release to trigger a build though.

Edit: Just realized the version was bumped when Travis CI builds and initial support for macOS was added despite having no code changes.

**Comment by dominikWin** [comment]
Okay, building now (although I'd imagine there's some contention for actions workers on macOS so this could take a while)

**Pull request merged**
