### PR TITLE
Fix thread panic when bag file has no data points

### PR DESCRIPTION
**Pull request by richiksc**
Often, if the robot code crashes, the bag file will be "empty" - It will have headers but no data points. When they are sent through badlogvis, it crashes with a thread panic:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/graph.rs:84:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This PR changes the unsafe `unwrap` on the `min_y_local` value to use a `match` statement and exit gracefully with a helpful error message:

```
error: No data points found in bag file! Robot code may have ended early.
```

### CODE REVIEW

**Comment by dominikWin** [comment]
Patch looks good, I'm not sure about including the vscode launch file though

**Comment by richiksc** [comment]
> Patch looks good, I'm not sure about including the vscode launch file though

Sure, I can add it to .gitignore and remove from repository

**Comment by richiksc** [comment]
@dominikWin file is ignored.

**Comment by richiksc** [comment]
@dominikWin Thanks!

**Pull request merged**
